export const TODO = {
  TODO_DELETE: "TODO_DELETE",
  TODO_EDIT: "TODO_EDIT",
  TODO_ADD: "TODO_ADD",
  TODO_DONE: "TODO_DONE",
  TODO_LOADING: "TODO_LOADING",
  TODO_ERROR: "TODO_ERROR",
  TODO_FILTER: "TODO_FILTER",
  TODO_FETCH_COMPLETE: 'TODO_FETCH_COMPLETE'
};

export const USER = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOADING: 'USER_LOADING',
  USER_ERROR: 'USER_ERROR',
  USER_SIGNOUT: 'USER_SIGNOUT'
};